spring.application.name=UngDungXemPhim

# 1. Database Connection (DataSource)
spring.datasource.url=jdbc:mariadb://localhost:3306/udphim
spring.datasource.username=root
spring.datasource.password=123456a@
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# 2. JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Optional
spring.cache.type=redis

# ===================== ELASTICSEARCH =====================
spring.elasticsearch.uris=http://localhost:9200

# ===================== CACHE CONFIG =====================
spring.cache.redis.time-to-live=60000
spring.cache.redis.cache-null-values=false

# ===================== LOG DEBUG =====================
logging.level.org.springframework.cache=DEBUG

#Kafka
# server
spring.kafka.bootstrap-servers=localhost:9092

# ========== CONSUMER ==========
spring.kafka.consumer.group-id=movie-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Cho phép deserialize object
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# ========== PRODUCER ==========
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

jwt.secret_key = lkR8PzBAq9qfXz84Vf9im45r0R0dQL177J5FNuapHaWwtNz2epnejTubyelqrioN52eH3Vs9P12Z2MFo6invjl